package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: 2016-DEC-14  03:13:36 PM
 */
public class PostNoMatchMenu extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for PostNoMatchMenu.
    */
    public PostNoMatchMenu() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("dtmf");
        setBuiltin(false);
        setFileName("PostNoMatchMenu.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

